### ISSUE TITLE
How to copy the tab to clipboard

### ISSUE THREAD

**Issue by GameHerobrine** [adriweb/NspireLuaScriptExtractor#1]
Maybe I am dumb but idk how to copy tab to the clipboard....

**Comment by adriweb** [comment]
Just right click on the tab, in the software once you opened the .tns file.
Note that this hasn't been tested in quite a while. I don't know if it still works.

![image](https://user-images.githubusercontent.com/660896/77462539-a06cbb80-6dda-11ea-8c1b-6b593995ee4f.png)

**Comment by GameHerobrine** [comment]
it works, thanks
