### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by blakeyoung81** [adriweb/NspireLuaScriptExtractor#2]
I opened the tns file in sublime text editor, copied it all, and the program didn't recognize the code. What am I doing wrong? The jar file ran correctly I think. please let me know.

**Comment by blakeyoung81** [comment]
What do you mean by copy the tab where the TNS file is exactly. Copy the code? or something else? please let me know.

**Comment by adriweb** [comment]
See here: https://github.com/adriweb/NspireLuaScriptExtractor/issues/1#issuecomment-603426267
