### ISSUE TITLE
No copy button

### ISSUE THREAD

**Issue by blakeyoung81** [adriweb/NspireLuaScriptExtractor#3]
Hello, sorry to disturb you again. I just installed teacher viewer on two machines and in neither is there a copy button as displayed in the issue #1 thread. It’s greyed out.

**Comment by adriweb** [comment]
Did you right click on it?
You can also select it and press Ctrl-C (or Cmd-C on mac).

If that doesn't work, I can't help sorry.

**Comment by blakeyoung81** [comment]
THanks for your response. I've spent the last five hours programming and
found your username a couple of times on different TI sites. It's awesome
that you're involved in the community. It works!! But I figured out one
thing. There are some TNS files that allow you to copy while others don't.
I tried to run the code my own document and I could copy it fine, but then
when I tried it with a tns i downloaded from the internet the copy button
went away. It's very strange. Your program works, it's quite elegant I'd
like to add.

However, do you know why the copy button isn't always there?

Thanks for your work in the TI community.

**Comment by adriweb** [comment]
Thanks for the kind words :)
But yes maybe it's a read-only setting somewhere in the document (I believe authors can set that). I haven't tested that so I guess I can't really help you with that specific case sorry.
